GoogleCloudPlatform/genai-for-marketing

.gitignore, app/override.toml, app/utils_standalone_image_gen.py
hi, adding some fix and addition as below:
- fix imagen endpoint
- add service account override
thanks!
=> quick fix on imagen endpoint, add sa override

backend_apis/README.md, backend_apis/app/body_schema.py, backend_apis/app/config.toml, backend_apis/app/main.py
1.  Translation API with or without source language input , with split and translate logic for larger text.
2.  Content Generation API for Email, Webpost, AssetGroup, and SocialMedia. It takes theme, context and some optional parameter to generate text and also generates images if generate_images marked true.
=> Adding Translation API and Content Generation API

app/app_config.toml
age bucket defaults modification for main branch config
=> modifies age_bucket

README.md
=> Fixed some typos in the readme

installation_scripts/tutorial.md
update installing script command in tutorial.md
=> update installing script command in tutorial.md

notebooks/brand_voice_tuned_bison.ipynb
Adds a brand voice tuning notebook for example usage
=> brand voice tuning notebook

tf/versions.tf
Updates terraform version to indicate solution version ID
=> doc: adds version indication

backend_apis/app/config.toml, frontend/firebase.json, frontend/src/app/home/home.component.html, frontend/src/app/home/home.component.ts, frontend/src/app/toggel-buttons/toggel-buttons.component.html, frontend/src/environments/environments.ts, installation_scripts/genai_marketing_automation.sh, tf/README.md, tf/app.tf, tf/backend.tf, tf/bq.tf, tf/gdrive.tf, tf/iam.tf, tf/locals.tf, tf/main.tf, tf/outputs.tf, tf/search-conversation.tf, tf/templates/config.toml.tftpl, tf/templates/environments.ts.tftpl, tf/variables.tf, tf/versions.tf
This PR includes the following changes:
- Adding licence to .tf files
- Changing the enablement of GCP services
- Standardizing configuration files
- Frontend minor fixes
=> terraform automation fixes

installation_scripts/backend_deployment.sh, tf/README.md, tf/app.tf, tf/gdrive.tf, tf/main.tf, tf/templates/Dockerfile.tftpl
This update includes updated Terraform documentation and minor fixes to the backend deployment process.
=> terraform deployment docs

tf/iam.tf
Adds roles to terraform
- Added BigQuery Job User
- Added BigQuery Data Viewer
- Added Cloud Datastore User
- Added Storage Object User
=> feat: adds roles to service account

tf/locals.tf
Adds enabling of artifact registry service
=> feat: enables artifact registry service

tf/README.md, tf/app.tf, tf/bq.tf, tf/gdrive.tf, tf/iam.tf, tf/locals.tf, tf/main.tf, tf/search-conversation.tf
This includes the following changes:
- Removing manual enablement of services to enforce resource creating after service enablement
- BigQuery dataset expiration changed
- Aditional docs
=> Terraform deployments improvements

backend_apis/app/utils_trendspotting.py, frontend/src/app/services/trendspotting.service.ts, frontend/src/app/trendspotting/trendspotting.component.html, frontend/src/app/trendspotting/trendspotting.component.ts
This commit fix:
- Changed to read only the *result* field from Google Trends top search terms
- Reducing *tone* parameter when consuming gdeltproject api to get more results
- Fixing loading status when requesting news summarization.
=> Hot Fix: Solving issues when consuming trendspotting sumarization news

infra/scripts/backend_deployment.sh, infra/scripts/frontend_deployment.sh
- Remove the overwriting of `config.toml` from output_config. 
- Make sure the deployment script for frontend is ran
=> Add: Fixes backend and frontend deployment issues

frontend/src/app/home/home.component.html, frontend/src/app/home/home.component.ts, frontend/src/environments/environments.ts, infra/app.tf, infra/templates/environments.ts.tftpl, manual-setup.md
Dialogflow CX variable fix and correct value for Dialogflow CX messenger
=> Fix: Dialogflow CX config

infra/README.md
- Add: Instructions for Vertex AI Agent Builder Datastores with chat agent
- Creates storage account
- Indexes data store
- Connects Dialogflow CX with data store
- Publishes the chat agent to work with UI
=> Vertex AI Agent Builder Datastores with chat agent

README.md, infra/README.md
- Remove variables.tf section from infra README.
- Add variables.tf configuration info to root README and polish up.
- Create a new "configuration" section in root README covering config.toml and variables.tf.
- Add more background about config.toml creation and (re-)configuration.
=> feat: Create configuration section in root README.

README.md, backend_apis/README.md, frontend/README.md
- Organize and cleanup root README.
- Polish Frontend README.
- Polish backend README.
=> Fix: Cleanup root, frontend, and backend READMEs.

backend_apis/app/main.py, infra/README.md, infra/templates/config.toml.tftpl
Changed image_model_name to Imagen3 and use its name from config.
=> Switched from Imagen2 to Imagen3

backend_apis/app/bulk_email_util.py, backend_apis/app/logger.py, backend_apis/app/main.py, infra/scripts/aux_data/data_gen.py, infra/templates/config.toml.tftpl
- Adding Custom Logging feature
- Changing news summary to Gemini
- Changing bulk email to Gemini
=> Change to Gemini and Add Logging

backend_apis/README.md, backend_apis/app/main.py
- **Remove:** `post_text_bison_generate` is not used anywhere in the app
- PR: Tested and has no impact to the app
=> Remove: `post_text_bison_generate` is not used anywhere in the app

backend_apis/README.md, backend_apis/app/main.py, backend_apis/app/utils_prompt.py
- Switch utils_prompt.async_predict_text_gemini to pull from config.
- Remove unused utils_prompt.async_predict_text_llm.
- Fix spelling of "campaing" in README and main.py.
- Fix campaign creation comment to remove Palm reference.
=> Fix: asyc_predict_text_gemini upgrade and remove unused code.

backend_apis/app/utils_trendspotting.py, frontend/src/app/services/trendspotting.service.ts, frontend/src/app/trendspotting/trendspotting.component.html, frontend/src/app/trendspotting/trendspotting.component.ts
Solving issues when consuming trendspotting sumarization news, this Commit  is already in main
=> Solving issues when consuming trendspotting sumarization news

backend_apis/app/utils_trendspotting.py, frontend/src/app/services/trendspotting.service.ts, frontend/src/app/trendspotting/trendspotting.component.html, frontend/src/app/trendspotting/trendspotting.component.ts
Merging from main to dev to keep commit history clean for subsequent merge of dev to main.
=> Hot Fix: Solve issues when consuming trendspotting sumarization news.

frontend/src/app/website-post/website-post.component.ts
Reduces number of Cloud Text to Speech Voices in Creative Studio > Webpage's Read Aloud picklist
=> reduces number of voice selection in web page read aloud
